### ISSUE TITLE
Many "duplicate identifier" errors in TypeScript app after upgrading from v0.24.0 to 0.26.0

### ISSUE THREAD

**Issue by suamikim** [aurelia/cli#520]
**I'm submitting a bug report**

* **Library Version:**
Framework `1.0.8`
CLI `0.26.0`

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.9.4

* **NPM Version:**
4.1.1

* **Browser:**
Chrome XX but it's not browser related

* **Language:**
TypeScript 2.1.5

**Current behavior:**
Building/running the app throws many typescript warnings which weren't their with CLI `0.24.0`.
Here's a partial output when running `au run --watch`:

```
typings\globals\url\index.d.ts(3,15): error TS2300: Duplicate identifier 'URLSearchParams'.
[11:06:05] gulp-notify: [Error running Gulp] Error: typings\globals\url\index.d.ts(3,15): error TS2300: Duplicate identifier 'URLSearchParams'.
typings\globals\whatwg-fetch\index.d.ts(6,13): error TS2451: Cannot redeclare block-scoped variable 'fetch'.
[11:06:05] gulp-notify: [Error running Gulp] Error: typings\globals\whatwg-fetch\index.d.ts(6,13): error TS2451: Cannot redeclare block-scoped variable 'fetch'.
typings\globals\whatwg-fetch\index.d.ts(8,14): error TS2300: Duplicate identifier 'HeadersInit'.
[11:06:05] gulp-notify: [Error running Gulp] Error: typings\globals\whatwg-fetch\index.d.ts(8,14): error TS2300: Duplicate identifier 'HeadersInit'.
typings\globals\whatwg-fetch\index.d.ts(9,15): error TS2300: Duplicate identifier 'Headers'.
[11:06:05] gulp-notify: [Error running Gulp] Error: typings\globals\whatwg-fetch\index.d.ts(9,15): error TS2300: Duplicate identifier 'Headers'.
typings\globals\whatwg-fetch\index.d.ts(26,14): error TS2300: Duplicate identifier 'BodyInit'.
[11:06:05] gulp-notify: [Error running Gulp] Error: typings\globals\whatwg-fetch\index.d.ts(26,14): error TS2300: Duplicate identifier 'BodyInit'.
typings\globals\whatwg-fetch\index.d.ts(38,14): error TS2300: Duplicate identifier 'RequestInfo'.
[11:06:05] gulp-notify: [Error running Gulp] Error: typings\globals\whatwg-fetch\index.d.ts(38,14): error TS2300: Duplicate identifier 'RequestInfo'.
typings\globals\whatwg-fetch\index.d.ts(39,15): error TS2300: Duplicate identifier 'Request'.
[11:06:05] gulp-notify: [Error running Gulp] Error: typings\globals\whatwg-fetch\index.d.ts(39,15): error TS2300: Duplicate identifier 'Request'.
typings\globals\whatwg-fetch\index.d.ts(59,11): error TS2300: Duplicate identifier 'Request'.
[11:06:05] gulp-notify: [Error running Gulp] Error: typings\globals\whatwg-fetch\index.d.ts(59,11): error TS2300: Duplicate identifier 'Request'.
typings\globals\whatwg-fetch\index.d.ts(65,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'referrerPolicy' must be of type 'string', but here has type 'ReferrerPolicy'.
[11:06:05] gulp-notify: [Error running Gulp] Error: typings\globals\whatwg-fetch\index.d.ts(65,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'referrerPolicy' must be of type 'string', but here has type 'ReferrerPolicy'.
typings\globals\whatwg-fetch\index.d.ts(66,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'mode' must be of type 'string', but here has type 'RequestMode'.
[11:06:05] gulp-notify: [Error running Gulp] Error: typings\globals\whatwg-fetch\index.d.ts(66,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'mode' must be of type 'string', but here has type 'RequestMode'.
typings\globals\whatwg-fetch\index.d.ts(67,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'credentials' must be of type 'string', but here has type 'RequestCredentials'.
[11:06:05] gulp-notify: [Error running Gulp] Error: typings\globals\whatwg-fetch\index.d.ts(67,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'credentials' must be of type 'string', but here has type 'RequestCredentials'.
typings\globals\whatwg-fetch\index.d.ts(68,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'cache' must be of type 'string', but here has type 'RequestCache'.
[11:06:05] gulp-notify: [Error running Gulp] Error: typings\globals\whatwg-fetch\index.d.ts(68,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'cache' must be of type 'string', but here has type 'RequestCache'.
typings\globals\whatwg-fetch\index.d.ts(69,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'redirect' must be of type 'string', but here has type 'RequestRedirect'.
[11:06:05] gulp-notify: [Error running Gulp] Error: typings\globals\whatwg-fetch\index.d.ts(69,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'redirect' must be of type 'string', but here has type 'RequestRedirect'.
typings\globals\whatwg-fetch\index.d.ts(71,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'window' must be of type 'any', but here has type 'null'.
[11:06:05] gulp-notify: [Error running Gulp] Error: typings\globals\whatwg-fetch\index.d.ts(71,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'window' must be of type 'any', but here has type 'null'.
typings\globals\whatwg-fetch\index.d.ts(83,15): error TS2300: Duplicate identifier 'Response'.
[11:06:05] gulp-notify: [Error running Gulp] Error: typings\globals\whatwg-fetch\index.d.ts(83,15): error TS2300: Duplicate identifier 'Response'.
typings\globals\whatwg-fetch\index.d.ts(102,11): error TS2300: Duplicate identifier 'Response'.
[11:06:05] gulp-notify: [Error running Gulp] Error: typings\globals\whatwg-fetch\index.d.ts(102,11): error TS2300: Duplicate identifier 'Response'.
typings\globals\whatwg-streams\index.d.ts(29,15): error TS2300: Duplicate identifier 'ReadableStream'.
[11:06:05] gulp-notify: [Error running Gulp] Error: typings\globals\whatwg-streams\index.d.ts(29,15): error TS2300: Duplicate identifier 'ReadableStream'.
__lib/lib.dom.d.ts(6945,11): error TS2300: Duplicate identifier 'Headers'.
[11:06:05] gulp-notify: [Error running Gulp] Error: __lib/lib.dom.d.ts(6945,11): error TS2300: Duplicate identifier 'Headers'.
__lib/lib.dom.d.ts(6954,13): error TS2300: Duplicate identifier 'Headers'.
[11:06:05] gulp-notify: [Error running Gulp] Error: __lib/lib.dom.d.ts(6954,13): error TS2300: Duplicate identifier 'Headers'.
__lib/lib.dom.d.ts(9321,11): error TS2300: Duplicate identifier 'ReadableStream'.
[11:06:05] gulp-notify: [Error running Gulp] Error: __lib/lib.dom.d.ts(9321,11): error TS2300: Duplicate identifier 'ReadableStream'.
__lib/lib.dom.d.ts(9327,13): error TS2300: Duplicate identifier 'ReadableStream'.
[11:06:05] gulp-notify: [Error running Gulp] Error: __lib/lib.dom.d.ts(9327,13): error TS2300: Duplicate identifier 'ReadableStream'.
__lib/lib.dom.d.ts(9343,11): error TS2300: Duplicate identifier 'Request'.
[11:06:05] gulp-notify: [Error running Gulp] Error: __lib/lib.dom.d.ts(9343,11): error TS2300: Duplicate identifier 'Request'.
__lib/lib.dom.d.ts(9360,13): error TS2300: Duplicate identifier 'Request'.
[11:06:05] gulp-notify: [Error running Gulp] Error: __lib/lib.dom.d.ts(9360,13): error TS2300: Duplicate identifier 'Request'.
__lib/lib.dom.d.ts(9365,11): error TS2300: Duplicate identifier 'Response'.
[11:06:05] gulp-notify: [Error running Gulp] Error: __lib/lib.dom.d.ts(9365,11): error TS2300: Duplicate identifier 'Response'.
__lib/lib.dom.d.ts(9376,13): error TS2300: Duplicate identifier 'Response'.
[11:06:05] gulp-notify: [Error running Gulp] Error: __lib/lib.dom.d.ts(9376,13): error TS2300: Duplicate identifier 'Response'.
__lib/lib.dom.d.ts(13858,11): error TS2300: Duplicate identifier 'URLSearchParams'.
[11:06:05] gulp-notify: [Error running Gulp] Error: __lib/lib.dom.d.ts(13858,11): error TS2300: Duplicate identifier 'URLSearchParams'.
__lib/lib.dom.d.ts(13885,13): error TS2300: Duplicate identifier 'URLSearchParams'.
[11:06:05] gulp-notify: [Error running Gulp] Error: __lib/lib.dom.d.ts(13885,13): error TS2300: Duplicate identifier 'URLSearchParams'.
__lib/lib.dom.d.ts(14893,18): error TS2451: Cannot redeclare block-scoped variable 'fetch'.
[11:06:05] gulp-notify: [Error running Gulp] Error: __lib/lib.dom.d.ts(14893,18): error TS2451: Cannot redeclare block-scoped variable 'fetch'.
__lib/lib.dom.d.ts(14898,6): error TS2300: Duplicate identifier 'BodyInit'.
[11:06:06] gulp-notify: [Error running Gulp] Error: __lib/lib.dom.d.ts(14898,6): error TS2300: Duplicate identifier 'BodyInit'.
__lib/lib.dom.d.ts(14919,6): error TS2300: Duplicate identifier 'HeadersInit'.
[11:06:06] gulp-notify: [Error running Gulp] Error: __lib/lib.dom.d.ts(14919,6): error TS2300: Duplicate identifier 'HeadersInit'.
__lib/lib.dom.d.ts(14929,6): error TS2300: Duplicate identifier 'RequestInfo'.
[11:06:06] gulp-notify: [Error running Gulp] Error: __lib/lib.dom.d.ts(14929,6): error TS2300: Duplicate identifier 'RequestInfo'.
```

Seems like some collision with the typings of the `whatwg-fetch` polyfil but I don't know how to resolve them since I have no idea where the file `__lib/lib.dom.d.ts` actually comes from and "who" it belongs to...

I've just updated the CLI, removed the `bluebird` configuration from `main.ts` and adjusted the `prepend` block of the `vendor-bundle` within `aurelia.json` as mentioned in the release notes for CLI `v0.25.0`.

How can I get rid of those errors?

**Ps.:** I'm relatively new to both Aurelia & TypeScript and am therefore not sure on wether this is actually a CLI issue or something I messed up but since everything was working as expected with `0.24.0` I suspect the CLI and hope for some clearance here ;)

**Comment by suamikim** [comment]
I manually installed some typings a few weeks ago according to the suggestions on some online blog (which I can't find anymore...) to fix some issues I had at that time. Removing them now solved my issues...

**Comment by AStoker** [comment]
@JeroenVinke recently added some logging in place that normally would have killed the actual watch command. Could be that that might be happening? @JeroenVinke, what do you think?

**Comment by GBSal** [comment]
I am having the same issue. what is the fix then

**Comment by suamikim** [comment]
@GBSal I'm sorry but I can't remember the details anymore. I can only tell you that I've uninstalled some manually installed typings as mentioned in my [comment on Mar 5](https://github.com/aurelia/cli/issues/520#issuecomment-284221249)...

**Comment by leebenson** [comment]
Try `npm i -D @types/node`

**Comment by Alexander-Taran** [comment]
I'd suggest renaming the typings directory and checking if everything builds without it.. and go from there..
