### ISSUE TITLE
The export keyword can only be used with the module goal

### ISSUE THREAD

**Issue by nenadvicentic** [aurelia/cli#1198]
**I'm submitting a bug report**

* **Library Version:**
3.0.1

**Please tell us about your environment:**
* **Operating System:**
Windows 11

* **Node Version:**
v16.14.0

* **NPM Version:**
8.3.1

* **Language:**
TypeScript 4.7.4

* **Loader/bundler:**
RequireJS

**Current behavior:**
After upgrade from Aurelia CLI 2.0.3 to 3.0.1, `au build` breaks with the message:

> ParseError [SyntaxError]: [241:6]: The export keyword can only be used with the module goal

* **What is the expected behavior?**

Continue to successfully bundle the project, as Aurelia CLI 2.0.3 did.

Full stack trace:
```
ERROR [BundledSource] Could not convert to AMD module, skipping WebSite\ClientApp\node_modules\latlon-geohash\latlon-geohash.js
ERROR [BundledSource] Error was: Error: Cannot find module '@babel/plugin-transform-modules-amd'
Require stack:
- WebSite\ClientApp\node_modules\aurelia-cli\node_modules\@babel\core\lib\config\files\plugins.js
- WebSite\ClientApp\node_modules\aurelia-cli\node_modules\@babel\core\lib\config\files\index.js
- WebSite\ClientApp\node_modules\aurelia-cli\node_modules\@babel\core\lib\index.js
- WebSite\ClientApp\node_modules\aurelia-cli\lib\build\amodro-trace\read\es.js
- WebSite\ClientApp\node_modules\aurelia-cli\lib\build\bundled-source.js
- WebSite\ClientApp\node_modules\aurelia-cli\lib\build\bundler.js
- WebSite\ClientApp\node_modules\aurelia-cli\lib\build\index.js
- WebSite\ClientApp\node_modules\aurelia-cli\lib\index.js
- C:\Users\nvicentic\AppData\Roaming\npm\node_modules\aurelia-cli\bin\aurelia-cli.js
ERROR [Bundler] Failed to do transforms
INFO [Bundler] SyntaxError: [241:6]: The export keyword can only be used with the module goal
{
  uid: 10,
  name: 'writeBundles',
  branch: false,
  error: ParseError [SyntaxError]: [241:6]: The export keyword can only be used with the module goal
      at report (WebSite\ClientApp\node_modules\meriyah\dist\meriyah.cjs:185:11)
      at parseStatementListItem (WebSite\ClientApp\node_modules\meriyah\dist\meriyah.cjs:4860:13)
      at parseStatementList (WebSite\ClientApp\node_modules\meriyah\dist\meriyah.cjs:4809:25)
      at parseSource (WebSite\ClientApp\node_modules\meriyah\dist\meriyah.cjs:4776:16)
      at Object.parseScript (WebSite\ClientApp\node_modules\meriyah\dist\meriyah.cjs:8775:12)
      at Function.parse.usesAmdOrRequireJs (WebSite\ClientApp\node_modules\aurelia-cli\lib\build\amodro-trace\lib\parse.js:553:26)
      at WebSite\ClientApp\node_modules\aurelia-cli\lib\build\amodro-trace\write\defines.js:57:28
      at WebSite\ClientApp\node_modules\aurelia-cli\lib\build\amodro-trace\write\all.js:27:14
      at Array.reduce (<anonymous>)
      at WebSite\ClientApp\node_modules\aurelia-cli\lib\build\amodro-trace\write\all.js:26:29 {
    index: 8378,
    line: 241,
    column: 6,
    description: '[241:6]: The export keyword can only be used with the module goal',
    loc: { line: 241, column: 6 }
  },
  duration: [ 0, 794769700 ],
  time: 1658846812804
}
{
  uid: 0,
  name: '<series>',
  branch: true,
  error: ParseError [SyntaxError]: [241:6]: The export keyword can only be used with the module goal
      at report (WebSite\ClientApp\node_modules\meriyah\dist\meriyah.cjs:185:11)
      at parseStatementListItem (WebSite\ClientApp\node_modules\meriyah\dist\meriyah.cjs:4860:13)
      at parseStatementList (WebSite\ClientApp\node_modules\meriyah\dist\meriyah.cjs:4809:25)
      at parseSource (WebSite\ClientApp\node_modules\meriyah\dist\meriyah.cjs:4776:16)
      at Object.parseScript (WebSite\ClientApp\node_modules\meriyah\dist\meriyah.cjs:8775:12)
      at Function.parse.usesAmdOrRequireJs (WebSite\ClientApp\node_modules\aurelia-cli\lib\build\amodro-trace\lib\parse.js:553:26)
      at WebSite\ClientApp\node_modules\aurelia-cli\lib\build\amodro-trace\write\defines.js:57:28
      at WebSite\ClientApp\node_modules\aurelia-cli\lib\build\amodro-trace\write\all.js:27:14
      at Array.reduce (<anonymous>)
      at WebSite\ClientApp\node_modules\aurelia-cli\lib\build\amodro-trace\write\all.js:26:29 {
    index: 8378,
    line: 241,
    column: 6,
    description: '[241:6]: The export keyword can only be used with the module goal',
    loc: { line: 241, column: 6 }
  },
  duration: [ 3, 636796700 ],
  time: 1658846812808
}
ParseError [SyntaxError]: [241:6]: The export keyword can only be used with the module goal
    at report (WebSite\ClientApp\node_modules\meriyah\dist\meriyah.cjs:185:11)
    at parseStatementListItem (WebSite\ClientApp\node_modules\meriyah\dist\meriyah.cjs:4860:13)
    at parseStatementList (WebSite\ClientApp\node_modules\meriyah\dist\meriyah.cjs:4809:25)
    at parseSource (WebSite\ClientApp\node_modules\meriyah\dist\meriyah.cjs:4776:16)
    at Object.parseScript (WebSite\ClientApp\node_modules\meriyah\dist\meriyah.cjs:8775:12)
    at Function.parse.usesAmdOrRequireJs (WebSite\ClientApp\node_modules\aurelia-cli\lib\build\amodro-trace\lib\parse.js:553:26)
    at WebSite\ClientApp\node_modules\aurelia-cli\lib\build\amodro-trace\write\defines.js:57:28
    at WebSite\ClientApp\node_modules\aurelia-cli\lib\build\amodro-trace\write\all.js:27:14
    at Array.reduce (<anonymous>)
    at WebSite\ClientApp\node_modules\aurelia-cli\lib\build\amodro-trace\write\all.js:26:29 {
  index: 8378,
  line: 241,
  column: 6,
  description: '[241:6]: The export keyword can only be used with the module goal',
  loc: { line: 241, column: 6 }
}
```

**Comment by 3cp** [comment]
> Cannot find module '@babel/plugin-transform-modules-amd'

Sounds like your node_modules is broken. Can you try clean them up (plus lock file) and try again?

**Comment by 3cp** [comment]
FYI, that babel amd package is a dep of aurelia-cli.
```
huocp@Chunpengs-MacBook-Pro ~/p/at> npm ls @babel/plugin-transform-modules-amd
at@0.1.0 /Users/huocp/playground/at
└─┬ aurelia-cli@3.0.1
  └── @babel/plugin-transform-modules-amd@7.18.6

```

**Comment by nenadvicentic** [comment]
@3cp After removing complete `node_modules` folder and `yarn.lock` file, then re-running `yarn`, `au build` started to work.

**Comment by 3cp** [comment]
Cheers
