### ISSUE TITLE
aurelia-cli TypeError: require.resolve.paths is not a function

### ISSUE THREAD

**Issue by WalterEbbers** [aurelia/cli#990]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-beta6

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.11.2

* **NPM Version:**
3.10.10

* **Browser:**
Not using a browser yet, 

* **Language:**
Typescript 3.2.1

* **Loader/bundler:**
webpack

**Current behavior:**
After updating aurelia cli from 0.32.0 to 1.0.0-beta6  when trying to build i receive the following error:                                      ^
TypeError: require.resolve.paths is not a function
    at Object.<anonymous> (Z:\xx\node_modules\aurelia-cli\lib\build\utils.js:17:39)
Line 17: const PACKAGE_PATHS = require.resolve.paths('not-core/');

**What is the expected behavior?**
i expected the update to go flawlessly.

**Steps to reproduce:**
1. What i did was create a new aurelia webpack typescript project with au - new.
2. ran ncu(npm-check-updates) to check if there where updates and ran ncu -u to upgrade my package.json with new versions. 
3. After that i ran npm update to update the npm packages
4. when that was done i tried au build --watch which failed with the error i mentioned above. 

 **What is the motivation / use case for changing the behavior?**
We are building a new Aurelia project and wanted to use the most recent available packages to build on.

**Comment by huochunpeng** [comment]
Cli v1 now requires nodejs v8.9.0+.

**Comment by zewa666** [comment]
might be a good idea to add the check at the beginning of the cli and throw a nicer error

**Comment by WalterEbbers** [comment]
@huochunpeng thnx will try that.

@zewa666  yeah would a good idea! a requirements check of some sorts.

**Comment by huochunpeng** [comment]
It does check, I guess you have not upgraded global cli?

`npm i -g aurelia-cli` then try again same command.

**Comment by WalterEbbers** [comment]
nope had not upgraded global cli. 
Thnx. 
running 1.0.0-beta.7 right now. 
Walked into another issue, but will find out what that is first, and create new issue if there is none. 

ty for the help!
