### ISSUE TITLE
Aurelia CLI is broken in 0.3.0

### ISSUE THREAD

**Issue by shabalin** [aurelia/cli#150]
Here is what I am getting after update to 0.3.0

```bash
$ aurelia
module.js:338
    throw err;
          ^
Error: Cannot find module 'babel-runtime/helpers/create-class'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/pavel/work/badirah/checl/skeleton-navigation/node_modules/aurelia-cli/dist/index.js:3:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

Npm info

```
$ npm view aurelia-cli

{ name: 'aurelia-cli',
  description: 'The command line tooling for Aurelia, used for creating projects, scaffolding, bundling and more.',
  'dist-tags': { latest: '0.3.0' },
  versions: [ '0.0.0', '0.1.0', '0.1.1', '0.1.2', '0.2.0', '0.2.1', '0.3.0' ],
  maintainers: 'ahmedshuhel <shuhel@ymail.com>',
  time:
   { modified: '2015-08-12T08:58:15.795Z',
     created: '2015-03-04T21:24:34.568Z',
     '0.0.0': '2015-03-04T21:24:34.568Z',
     '0.1.0': '2015-03-27T06:57:52.926Z',
     '0.1.1': '2015-03-29T18:33:28.013Z',
     '0.1.2': '2015-04-21T18:05:55.113Z',
     '0.2.0': '2015-05-27T22:32:43.464Z',
     '0.2.1': '2015-06-20T20:07:41.566Z',
     '0.3.0': '2015-08-12T08:58:15.795Z' },
  license: 'MIT',
  readmeFilename: 'README.md',
  homepage: 'http://aurelia.io',
  keywords: [ 'aurelia', 'cli', 'bundle', 'scaffold' ],
  repository: { type: 'git', url: 'https://github.com/aurelia/cli' },
  author: 'Rob Eisenberg <rob@bluespire.com> (http://robeisenberg.com/)',
  bugs: { url: 'https://github.com/aurelia/cli/issues' },
  version: '0.3.0',
  scripts:
   { test: 'mocha --compilers js:babel/register',
     tdd: 'mocha --compilers js:babel/register -w' },
  bin: { aurelia: 'bin/aurelia.js' },
  main: 'dist/commonjs/index.js',
  dependencies:
   { 'babel-core': '^5.8.3',
     bluebird: '^2.9.25',
     chalk: '^1.0.0',
     'child-process-promise': '^1.1.0',
     commander: '^2.8.1',
     'download-github-repo': '^0.1.3',
     github: '^0.2.4',
     glob: '^5.0.9',
     globby: '^2.0.0',
     handlebars: '^3.0.3',
     inquirer: '^0.8.5',
     jspm: '^0.16.0-beta.7',
     liftoff: '^2.1.0',
     lodash: '^3.10.1',
     minimist: '^1.1.1',
     mkdirp: '^0.5.1',
     npm: '^2.10.1',
     request: '^2.60.0',
     'systemjs-builder': '^0.13.0',
     whacko: '^0.18.1',
     winston: '^1.0.0' },
  devDependencies:
   { babel: '^5.4.7',
     'babel-runtime': '^5.8.19',
     chai: '^2.3.0',
     gulp: '^3.8.11',
     'gulp-babel': '^5.1.0',
     injectr: '^0.5.1',
     mocha: '^2.2.5',
     sinon: '^1.14.1' },
  gitHead: '180bc216e1115cc7fab4750152e830bc3161eaca',
  dist:
   { shasum: 'f097082032950fdd2ce1c63637d0c7d1cf0d0ea3',
     tarball: 'http://registry.npmjs.org/aurelia-cli/-/aurelia-cli-0.3.0.tgz' },
  directories: {} }
```

**Comment by shabalin** [comment]
Seems like moving "babel-runtime": "^5.8.19" from devDependencies to dependencies fixes the issue.

**Comment by ahmedshuhel** [comment]
@shabalin you are right. We just have a `fix` release. v0.3.1. Please install that.
